<?php

namespace webdoka\yiiecommerce\common\models;

use Yii;
use app\models\User;
use webdoka\yiiecommerce\common\queries\AccountQuery;

/**
 * This is the model class for table "accounts".
 *
 * @property integer $id
 * @property integer $name
 * @property double $balance
 * @property integer $currency_id
 * @property integer $user_id
 * @property integer $default
 *
 * @property User $user
 * @property Currency $currency
 */
class Account extends \yii\db\ActiveRecord
{
    const LIST_ACCOUNT = 'shopListAccount';
    const VIEW_ACCOUNT = 'shopViewAccount';
    const CREATE_ACCOUNT = 'shopCreateAccount';
    const UPDATE_ACCOUNT = 'shopUpdateAccount';
    const DELETE_ACCOUNT = 'shopDeleteAccount';
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'accounts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['currency_id', 'user_id', 'name'], 'required'],
            [['balance'], 'number'],
            [['name'], 'string', 'max' => 255],
            [['currency_id', 'user_id'], 'integer'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['currency_id'], 'exist', 'skipOnError' => true, 'targetClass' => Currency::className(), 'targetAttribute' => ['currency_id' => 'id']],
            [['default'], 'validateDefault'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'balance' => 'Balance',
            'currency_id' => 'Currency ID',
            'user_id' => 'User ID',
        ];
    }

    /**
     * Validates $default
     */
    public function validateDefault()
    {
        // Only one account can be default
        if ($this->default == 0) {
            if (!self::find()->andWhere(['user_id' => $this->user_id])->andWhere(['<>', 'id', $this->id])->default1()->one()) {
                $this->addError('default', 'At least one account must be in default.');
            }
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurrency()
    {
        return $this->hasOne(Currency::className(), ['id' => 'currency_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransactions()
    {
        return $this->hasMany(Transaction::className(), ['account_id' => 'id'])->orderBy(['id' => 'desc']);
    }

    /**
     * Delete linked transactions
     * @return bool
     */
    public function beforeDelete()
    {
        $this->unlinkAll('transactions', true);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return AccountQuery
     */
    public static function find()
    {
        return new AccountQuery(get_called_class());
    }
}
